import os
import logging
import argparse
from pathlib import Path

import numpy as np
import napari
import dbdicom as db
from tqdm import tqdm

from ibeat_kidney_shape.utils import data, edit

MODULE_DIR = Path(__file__).resolve().parent

SITE = {
    '1128': 'Bari',
    '2128': 'Bordeaux',
    '6128': 'Bordeaux',
    '3128': 'Exeter',
    '4128': 'Leeds',
    '7128': 'Sheffield',
    '5128': 'Turku',
}


def edit_mask_with_napari(image_3d: np.ndarray, mask_3d: np.ndarray) -> np.ndarray:
    """
    Launches Napari to manually edit a 3D mask over a 3D image.

    Parameters:
    - image_3d: numpy.ndarray
        A 3D image array (shape: Z, Y, X)
    - mask_3d: numpy.ndarray
        A 3D mask array (shape: Z, Y, X)

    Returns:
    - edited_mask: numpy.ndarray
        The modified mask after editing in Napari.
    """
    if image_3d.shape != mask_3d.shape:
        raise ValueError("Image and mask must have the same shape.")
    
    # Ensure label image is integer type
    mask_3d = mask_3d.astype(np.int32)

    # Launch Napari
    viewer = napari.Viewer()

    # Display the image and the mask
    viewer.add_image(image_3d, name='Image')
    mask_layer = viewer.add_labels(mask_3d, name='Mask')
    mask_layer.mode = 'paint'
    mask_layer.opacity = 0.4
    mask_layer.brush_size = 6

    # Set 2D slicing and coronal orientation for (X, Y, Z) image
    viewer.dims.ndisplay = 2
    viewer.dims.order = [2, 1, 0]  # Y, Z, X order for coronal view

    # Run Napari event loop
    napari.run()

    # Return the edited mask
    return mask_layer.data



def run(build):

    logging.basicConfig(
        filename=os.path.join(build, 'kidney_shape', 'stage_3_edit.log'),
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s'
    )

    dir_data = os.path.join(build, 'dixon', 'stage_5_clean_dixon_data') 
    dir_masks = os.path.join(build, 'kidney_shape', 'stage_1_segment') 
    dir_output = os.path.join(build, 'kidney_shape', 'stage_3_edit')
    os.makedirs(dir_output, exist_ok=True)

    for database in ['Controls', 'Patients']:
        db_data = os.path.join(dir_data, database) 
        db_masks = os.path.join(dir_masks, database) 
        db_edit = os.path.join(dir_output, database) 
        run_db(db_data, db_masks, db_edit)


def run_db(db_data, db_masks, db_edit):

    # List of selected dixon series
    record = data.dixon_record(MODULE_DIR)

    # Loop over the autogenerated masks
    for mask_series in tqdm(db.series(db_masks), 'Displaying masks..'):

        # Get descriptors
        patient, study = mask_series[1], mask_series[2][0]
        sequence = data.dixon_series_desc(record, patient, study)

        # Input and output series
        series_op = [db_data, patient, (study, 0), (sequence + '_out_phase', 0)]
        auto_mask_series = [db_masks, patient, (study, 0), ('kidney_masks', 0)]
        edited_mask_series = [db_edit, patient, (study, 0), (f'kidney_masks', 0)]
        
        # Skip if the edited masks already exist
        if db.exists(edited_mask_series):
            continue

        try:

            # Read data
            op = db.volume(series_op)
            auto_mask = db.volume(auto_mask_series)

            # Edit mask
            edited_mask = edit_mask_with_napari(op.values, auto_mask.values)

            # Save results and log
            vol = (edited_mask.astype(np.int16), auto_mask.affine)
            db.write_volume(vol, edited_mask_series, ref=series_op)
            logging.info(f"Successfully edited mask for {patient}, {study}.")#

        except:

            logging.exception(f"Error editing mask for {patient}, {study}.")


if __name__=='__main__':

    BUILD = r'C:\Users\md1spsx\Documents\Data\iBEAt_Build'
    
    parser = argparse.ArgumentParser()
    parser.add_argument("--build", type=str, default=BUILD, help="Build folder")
    args = parser.parse_args()

    run(args.build)